sudo: required

dist: trusty

language: python

python:
  - 3.6

branches:
  only:
    - master

addons:
    apt:
      update: true

env:
  global:
    - JOBS=1

cache:
  directories:
    - "node_modules"

before_install:
  - pip install -U pip
  - npm config set spin false

install:
  - pip install awscli

before_script:
  - npm i -g npm@latest
  - npm i

script:
  - npm test

notifications:
  email:
    on_failure: change
    on_success: change