service: serverless-cars-api

provider:
  name: aws
  stage: beta
  region: us-west-2
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: cars/create.handler
    events:
      - http:
          path: cars
          method: post
          cors: true
  list:
    handler: cars/list.handler
    events:
      - http:
          path: cars
          method: get
          cors: true
  get:
    handler: cars/get.handler
    events:
      - http:
          path: cars/{id}
          method: get
          cors: true
  update:
    handler: cars/update.handler
    events:
      - http:
          path: cars/{id}
          method: put
          cors: true
  delete:
    handler: cars/delete.handler
    events:
      - http:
          path: cars/{id}
          method: delete
          cors: true
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}